# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
os:
  - linux
  - osx
r:
  - 3.4
  - release
  - devel
matrix:
  exclude:
  - r: 3.4
    os: osx
  - r: devel
    os: osx
notifications:
  email:
    on_success: change
    on_failure: change
r_packages:
  - covr
  - testthat
r_github_packages:
  - rstub/swephRdata
after_success:
  - test "$TRAVIS_R_VERSION_STRING" = "release" && Rscript -e 'covr::codecov()' || true
before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  on:
    condition: $TRAVIS_R_VERSION_STRING = release
